USE [master]
GO
/****** Object:  Database [PV221Chat]    Script Date: 2024-09-25 16:24:59 ******/
CREATE DATABASE [PV221Chat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PV221Chat', FILENAME = N'C:\Users\User\PV221Chat.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PV221Chat_log', FILENAME = N'C:\Users\User\PV221Chat_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PV221Chat] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PV221Chat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PV221Chat] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PV221Chat] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PV221Chat] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PV221Chat] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PV221Chat] SET ARITHABORT OFF 
GO
ALTER DATABASE [PV221Chat] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PV221Chat] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PV221Chat] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PV221Chat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PV221Chat] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PV221Chat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PV221Chat] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PV221Chat] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PV221Chat] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PV221Chat] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PV221Chat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PV221Chat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PV221Chat] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PV221Chat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PV221Chat] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PV221Chat] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PV221Chat] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PV221Chat] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PV221Chat] SET  MULTI_USER 
GO
ALTER DATABASE [PV221Chat] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PV221Chat] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PV221Chat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PV221Chat] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PV221Chat] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PV221Chat] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PV221Chat] SET QUERY_STORE = OFF
GO
USE [PV221Chat]
GO
/****** Object:  Table [dbo].[BlockedUsers]    Script Date: 2024-09-25 16:24:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BlockedUsers](
	[BlockId] [int] IDENTITY(1,1) NOT NULL,
	[BlockedByUserId] [int] NULL,
	[BlockedUserId] [int] NULL,
	[ChatId] [int] NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[BlockId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BlogPages]    Script Date: 2024-09-25 16:24:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BlogPages](
	[BlogId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](255) NOT NULL,
	[Content] [nvarchar](max) NULL,
	[AuthorId] [int] NULL,
	[CreatedAt] [datetime] NULL,
	[Type] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BlogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BlogSubscriptions]    Script Date: 2024-09-25 16:24:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BlogSubscriptions](
	[SubscriptionId] [int] IDENTITY(1,1) NOT NULL,
	[BlogId] [int] NULL,
	[UserId] [int] NULL,
	[SubscribedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[SubscriptionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Chats]    Script Date: 2024-09-25 16:24:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Chats](
	[ChatId] [int] IDENTITY(1,1) NOT NULL,
	[ChatName] [nvarchar](100) NULL,
	[ChatType] [nvarchar](50) NOT NULL,
	[IsOpen] [bit] NOT NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ChatId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Messages]    Script Date: 2024-09-25 16:24:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Messages](
	[MessageId] [int] IDENTITY(1,1) NOT NULL,
	[ChatId] [int] NULL,
	[SenderId] [int] NULL,
	[MessageText] [nvarchar](max) NOT NULL,
	[SentAt] [datetime] NULL,
	[IsDeleted] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[MessageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ModerationLogs]    Script Date: 2024-09-25 16:24:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ModerationLogs](
	[LogId] [int] IDENTITY(1,1) NOT NULL,
	[ModeratorId] [int] NULL,
	[Action] [nvarchar](100) NOT NULL,
	[TargetUserId] [int] NULL,
	[TargetChatId] [int] NULL,
	[ActionTakenAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[LogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Notifications]    Script Date: 2024-09-25 16:24:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Notifications](
	[NotificationId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[NotificationText] [nvarchar](255) NULL,
	[CreatedAt] [datetime] NULL,
	[IsRead] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[NotificationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserChats]    Script Date: 2024-09-25 16:24:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserChats](
	[UserChatId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[ChatId] [int] NULL,
	[IsAdmin] [bit] NULL,
	[MembershipStatus] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[UserChatId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserRatings]    Script Date: 2024-09-25 16:24:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserRatings](
	[RatingId] [int] IDENTITY(1,1) NOT NULL,
	[RatedUserId] [int] NULL,
	[RatedById] [int] NULL,
	[RatingScore] [int] NULL,
	[RatingComment] [nvarchar](255) NULL,
	[RatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[RatingId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 2024-09-25 16:24:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Nickname] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[PasswordHash] [nvarchar](256) NULL,
	[LoginProvider] [nvarchar](50) NULL,
	[ProviderUserId] [nvarchar](256) NULL,
	[Hobbies] [nvarchar](255) NULL,
	[Skills] [nvarchar](255) NULL,
	[BirthDate] [date] NULL,
	[AvatarUrl] [nvarchar](255) NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BlockedUsers] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[BlogPages] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[BlogSubscriptions] ADD  DEFAULT (getdate()) FOR [SubscribedAt]
GO
ALTER TABLE [dbo].[Chats] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Messages] ADD  DEFAULT (getdate()) FOR [SentAt]
GO
ALTER TABLE [dbo].[Messages] ADD  DEFAULT ((0)) FOR [IsDeleted]
GO
ALTER TABLE [dbo].[ModerationLogs] ADD  DEFAULT (getdate()) FOR [ActionTakenAt]
GO
ALTER TABLE [dbo].[Notifications] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Notifications] ADD  DEFAULT ((0)) FOR [IsRead]
GO
ALTER TABLE [dbo].[UserChats] ADD  DEFAULT ((0)) FOR [IsAdmin]
GO
ALTER TABLE [dbo].[UserChats] ADD  DEFAULT ('Pending') FOR [MembershipStatus]
GO
ALTER TABLE [dbo].[UserRatings] ADD  DEFAULT (getdate()) FOR [RatedAt]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[BlockedUsers]  WITH CHECK ADD FOREIGN KEY([BlockedByUserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[BlockedUsers]  WITH CHECK ADD FOREIGN KEY([BlockedUserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[BlockedUsers]  WITH CHECK ADD FOREIGN KEY([ChatId])
REFERENCES [dbo].[Chats] ([ChatId])
GO
ALTER TABLE [dbo].[BlogPages]  WITH CHECK ADD FOREIGN KEY([AuthorId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[BlogSubscriptions]  WITH CHECK ADD FOREIGN KEY([BlogId])
REFERENCES [dbo].[BlogPages] ([BlogId])
GO
ALTER TABLE [dbo].[BlogSubscriptions]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[Messages]  WITH CHECK ADD FOREIGN KEY([ChatId])
REFERENCES [dbo].[Chats] ([ChatId])
GO
ALTER TABLE [dbo].[Messages]  WITH CHECK ADD FOREIGN KEY([SenderId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[ModerationLogs]  WITH CHECK ADD FOREIGN KEY([ModeratorId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[ModerationLogs]  WITH CHECK ADD FOREIGN KEY([TargetUserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[ModerationLogs]  WITH CHECK ADD FOREIGN KEY([TargetChatId])
REFERENCES [dbo].[Chats] ([ChatId])
GO
ALTER TABLE [dbo].[Notifications]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[UserChats]  WITH CHECK ADD FOREIGN KEY([ChatId])
REFERENCES [dbo].[Chats] ([ChatId])
GO
ALTER TABLE [dbo].[UserChats]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[UserRatings]  WITH CHECK ADD FOREIGN KEY([RatedUserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[UserRatings]  WITH CHECK ADD FOREIGN KEY([RatedById])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[UserRatings]  WITH CHECK ADD CHECK  (([RatingScore]>=(1) AND [RatingScore]<=(5)))
GO
USE [master]
GO
ALTER DATABASE [PV221Chat] SET  READ_WRITE 
GO
